# Generated by Django 2.2 on 2020-09-20 00:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200912_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
